apiVersion: v1
kind: Service
metadata:
  name: reservation-svc
  namespace: jenkins-k8s-v2
  labels:
    app: reservation-svc
spec:
  type: LoadBalancer
  ports:
  - port: 8093
    targetPort: 8093
  selector:
    app: reservation-svc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservation-svc
  namespace: jenkins-k8s-v2
spec:
  selector:
    matchLabels:
      app: reservation-svc
  replicas: 1
  template:
    metadata:
      labels:
        app: reservation-svc
    spec:
      containers:
      - name: reservation
        image: namsing1/reservation-svc:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8093
