apiVersion: v1
kind: Service
metadata:
  name: reservation-svc
  namespace: helidon-deployment
  labels:
    app: itemreservation-msa
spec:
  type: NodePort
  ports:
  - port: 8093
    targetPort: 8093
    nodePort: 32046
  selector:
    app: itemreservation-msa
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservation-svc
  namespace: helidon-deployment
spec:
  selector:
    matchLabels:
      app: itemreservation-msa
  replicas: 1
  template:
    metadata:
      labels:
        app: itemreservation-msa
    spec:
      containers:
      - name: reservation
        image: namsing1/item-reservation:latest
        ports:
        - containerPort: 8093
